"""Per-store similarity modes (issue #114).

Every integration store supports two modes, fixed at construction:

- ``cosine`` (default): documents are L2-normalized at add time and
  queries at search time, so raw scores are true cosine similarity in
  [-1, 1], the (sim + 1) / 2 relevance mappings are correct, and
  threshold filtering works for embeddings of any magnitude.
- ``dot_product`` (opt-in): raw vectors, magnitude-aware ranking —
  exactly the pre-mode behavior.

Covered here:
- the three wave-8 threshold breakages as regression tests (non-unit
  embedders; fixed under cosine, pinned old-way under dot_product);
- reference-parity of cosine-mode ranking on non-unit embeddings;
- legacy side-cars written by pre-mode turbovec load as raw
  (dot_product) stores with unchanged scoring, from fixtures actually
  generated by the pre-mode code (tests/fixtures/legacy_pre_similarity);
- mode round-trip through save/load and mode-conflict handling;
- zero-vector handling; and mode-parameter validation.

Geometry helper: documents are built with exact target cosines against
the query direction, with gaps far above 4-bit quantization noise, and
wildly varying magnitudes so dot-product ranking would disagree.
"""
from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pytest

DIM = 16
FIXTURES = Path(__file__).parent / "fixtures" / "legacy_pre_similarity"


def directed_docs(
    cosines: list[float],
    mags: list[float],
    dim: int = DIM,
    seed: int = 7,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(docs, query)`` where ``docs[i]`` has exact cosine
    ``cosines[i]`` against ``query`` and L2 norm ``mags[i]``; ``query``
    is a unit vector."""
    rng = np.random.default_rng(seed)
    qhat = rng.standard_normal(dim)
    qhat /= np.linalg.norm(qhat)
    docs = []
    for c, m in zip(cosines, mags):
        r = rng.standard_normal(dim)
        r -= (r @ qhat) * qhat
        r /= np.linalg.norm(r)
        docs.append(m * (c * qhat + np.sqrt(1.0 - c * c) * r))
    return np.asarray(docs, dtype=np.float32), qhat.astype(np.float32)


# All-negative geometry: every raw inner product is < -1 (magnitudes
# 12 / 6 / 3 times cosines -0.2 / -0.6 / -0.98 give -2.4 / -3.6 / -2.94),
# so the legacy (sim + 1) / 2 mapping clamps everything to 0.0. The true
# cosines map to relevances 0.4 / 0.2 / 0.01.
NEG_COS = [-0.2, -0.6, -0.98]
NEG_MAGS = [12.0, 6.0, 3.0]

# All-positive-large geometry: raw inner products 380 / 50 / 4 all clamp
# to relevance 1.0 (indistinguishable); true cosines 0.95 / 0.5 / 0.1
# map to 0.975 / 0.75 / 0.55.
POS_COS = [0.95, 0.5, 0.1]
POS_MAGS = [400.0, 100.0, 40.0]

# Ranking-parity geometry: cosine order is 0, 3, 2, 7, 5, 1, 6, 4 while
# raw-dot order is completely different (e.g. doc 2 with cosine 0.45 and
# magnitude 11 out-scores doc 0 with cosine 0.9 and magnitude 0.5).
PARITY_COS = [0.9, -0.3, 0.45, 0.68, -0.75, 0.0, -0.52, 0.22]
PARITY_MAGS = [0.5, 30.0, 11.0, 2.0, 25.0, 7.0, 18.0, 0.9]


def load_expected() -> dict:
    with open(FIXTURES / "expected.json") as f:
        return json.load(f)


# =====================================================================
# LangChain
# =====================================================================


def _lc_store(docs: np.ndarray, query: np.ndarray, **kwargs):
    langchain_core = pytest.importorskip("langchain_core")  # noqa: F841
    from langchain_core.embeddings import Embeddings

    from turbovec.langchain import TurboQuantVectorStore

    class E(Embeddings):
        def embed_documents(self, ts):
            return [docs[int(t)].tolist() for t in ts]

        def embed_query(self, q):
            return query.tolist()

    store = TurboQuantVectorStore(embedding=E(), **kwargs)
    store.add_texts(
        [str(i) for i in range(len(docs))],
        ids=[f"d{i}" for i in range(len(docs))],
    )
    return store


def test_langchain_score_threshold_retriever_works_under_cosine_default():
    # Wave-8 breakage 1: with non-unit embeddings and all-negative raw
    # inner products, the score_threshold retriever returned [] because
    # every relevance clamped to 0.0. Under the cosine default the
    # genuine best matches survive a small threshold, best first.
    docs, query = directed_docs(NEG_COS, NEG_MAGS)
    store = _lc_store(docs, query)
    retriever = store.as_retriever(
        search_type="similarity_score_threshold",
        search_kwargs={"score_threshold": 0.05, "k": 3},
    )
    got = [d.id for d in retriever.invoke("q")]
    # True relevances ~0.4 / 0.2 / 0.01: the first two pass 0.05.
    assert got == ["d0", "d1"]


def test_langchain_relevance_scores_distinct_under_cosine_default():
    # The all-positive-large case: raw IPs 380 / 50 / 4 used to clamp
    # every relevance to 1.0 (no threshold could separate them). True
    # cosines give distinct, ordered relevances.
    docs, query = directed_docs(POS_COS, POS_MAGS)
    store = _lc_store(docs, query)
    pairs = store.similarity_search_with_relevance_scores("q", k=3)
    ids = [d.id for d, _ in pairs]
    scores = [s for _, s in pairs]
    assert ids == ["d0", "d1", "d2"]
    assert scores[0] > scores[1] > scores[2]
    for got, want in zip(scores, [0.975, 0.75, 0.55]):
        assert got == pytest.approx(want, abs=0.02)


def test_langchain_dot_product_mode_pins_old_threshold_behavior():
    # Explicit dot_product opt-in keeps the raw-inner-product scoring:
    # all-negative IPs below -1 still clamp to relevance 0.0 and the
    # threshold retriever returns [] — the documented magnitude-aware
    # trade-off of that mode.
    docs, query = directed_docs(NEG_COS, NEG_MAGS)
    store = _lc_store(docs, query, similarity="dot_product")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")  # "no relevant docs" UserWarning
        pairs = store.similarity_search_with_relevance_scores(
            "q", k=3, score_threshold=0.01
        )
    assert pairs == []
    # And raw scores stay raw inner products (magnitude-aware).
    raw = store.similarity_search_with_score("q", k=3)
    assert all(s < -1.0 for _, s in raw)


def test_langchain_cosine_ranking_matches_inmemory_reference():
    pytest.importorskip("langchain_core")
    from langchain_core.embeddings import Embeddings
    from langchain_core.vectorstores import InMemoryVectorStore

    docs, query = directed_docs(PARITY_COS, PARITY_MAGS)

    class E(Embeddings):
        def embed_documents(self, ts):
            return [docs[int(t)].tolist() for t in ts]

        def embed_query(self, q):
            return query.tolist()

    ref = InMemoryVectorStore(embedding=E())
    ref.add_texts(
        [str(i) for i in range(len(docs))],
        ids=[f"d{i}" for i in range(len(docs))],
    )
    ref_ids = [d.id for d, _ in ref.similarity_search_with_score("q", k=6)]

    store = _lc_store(docs, query)
    got_ids = [d.id for d, _ in store.similarity_search_with_score("q", k=6)]
    assert got_ids == ref_ids


def test_langchain_mode_round_trips_through_dump_load(tmp_path):
    docs, query = directed_docs(POS_COS, POS_MAGS)
    for mode in ("cosine", "dot_product"):
        store = _lc_store(docs, query, similarity=mode)
        before = [(d.id, s) for d, s in store.similarity_search_with_score("q", k=3)]
        store.dump(tmp_path / mode)

        from turbovec.langchain import TurboQuantVectorStore

        loaded = TurboQuantVectorStore.load(
            tmp_path / mode, embedding=store.embeddings
        )
        assert loaded.similarity == mode
        after = [(d.id, s) for d, s in loaded.similarity_search_with_score("q", k=3)]
        assert after == before


def test_langchain_legacy_sidecar_loads_as_dot_product_with_identical_scores():
    # Fixture generated by pre-mode turbovec (see fixtures/…/expected.json):
    # no `similarity` field in the side-car -> loads as dot_product and
    # scores exactly as the store that wrote it (tolerance only allows
    # for SIMD lane-order rounding across ISAs; identical bytes on the
    # writing machine).
    pytest.importorskip("langchain_core")
    from langchain_core.embeddings import Embeddings

    from turbovec.langchain import TurboQuantVectorStore

    exp = load_expected()
    query = np.asarray(exp["query"], dtype=np.float32)

    class E(Embeddings):
        def embed_documents(self, ts):
            raise AssertionError("not used")

        def embed_query(self, q):
            return query.tolist()

    store = TurboQuantVectorStore.load(FIXTURES / "langchain", embedding=E())
    assert store.similarity == "dot_product"
    got = [(d.id, s) for d, s in store.similarity_search_with_score("q", k=3)]
    for (gid, gscore), (wid, wscore) in zip(got, exp["langchain"]):
        assert gid == wid
        assert gscore == pytest.approx(wscore, rel=1e-6)


def test_langchain_zero_vectors_score_zero_under_cosine():
    pytest.importorskip("langchain_core")
    docs, query = directed_docs([0.5], [3.0])
    all_docs = np.vstack([docs, np.zeros((1, DIM), dtype=np.float32)])
    store = _lc_store(all_docs, query)
    got = store.similarity_search_with_score("q", k=2)
    scores = {d.id: s for d, s in got}
    assert scores["d0"] == pytest.approx(0.5, abs=0.02)
    assert scores["d1"] == pytest.approx(0.0, abs=1e-6)


def test_langchain_zero_query_scores_zero_under_cosine():
    pytest.importorskip("langchain_core")
    docs, _ = directed_docs([0.5, -0.5], [3.0, 7.0])
    store = _lc_store(docs, np.zeros(DIM, dtype=np.float32))
    got = store.similarity_search_with_score("q", k=2)
    assert len(got) == 2
    assert all(s == pytest.approx(0.0, abs=1e-6) for _, s in got)


def test_langchain_rejects_unknown_similarity():
    pytest.importorskip("langchain_core")
    from langchain_core.embeddings import Embeddings

    from turbovec.langchain import TurboQuantVectorStore

    class E(Embeddings):
        def embed_documents(self, ts):
            return [[0.0] * DIM for _ in ts]

        def embed_query(self, q):
            return [0.0] * DIM

    with pytest.raises(ValueError, match="similarity"):
        TurboQuantVectorStore(embedding=E(), similarity="euclidean")


def test_langchain_from_texts_forwards_similarity():
    docs, query = directed_docs([0.5], [3.0])
    pytest.importorskip("langchain_core")
    from langchain_core.embeddings import Embeddings

    from turbovec.langchain import TurboQuantVectorStore

    class E(Embeddings):
        def embed_documents(self, ts):
            return [docs[0].tolist() for _ in ts]

        def embed_query(self, q):
            return query.tolist()

    store = TurboQuantVectorStore.from_texts(["x"], E(), similarity="dot_product")
    assert store.similarity == "dot_product"
    [(_, score)] = store.similarity_search_with_score("q", k=1)
    # Raw inner product = mag * cos = 1.5, not the cosine 0.5.
    assert score == pytest.approx(1.5, abs=0.05)


# =====================================================================
# LlamaIndex
# =====================================================================


def _li_nodes(docs: np.ndarray):
    from llama_index.core.schema import TextNode

    return [
        TextNode(id_=f"n{i}", text=f"t{i}", embedding=docs[i].tolist())
        for i in range(len(docs))
    ]


def _li_query(query: np.ndarray, k: int):
    from llama_index.core.vector_stores.types import VectorStoreQuery

    return VectorStoreQuery(query_embedding=query.tolist(), similarity_top_k=k)


def test_llama_similarities_are_true_cosine_under_default():
    # LlamaIndex passes similarities straight through to consumers (e.g.
    # node postprocessors with similarity cutoffs). Under the cosine
    # default they are true cosines in [-1, 1] regardless of magnitude.
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    store = TurboQuantVectorStore()
    store.add(_li_nodes(docs))
    res = store.query(_li_query(query, 3))
    assert res.ids == ["n0", "n1", "n2"]
    for got, want in zip(res.similarities, POS_COS):
        assert got == pytest.approx(want, abs=0.02)


def test_llama_dot_product_mode_passes_raw_inner_products():
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    store = TurboQuantVectorStore(similarity="dot_product")
    store.add(_li_nodes(docs))
    res = store.query(_li_query(query, 3))
    raw = [c * m for c, m in zip(POS_COS, POS_MAGS)]  # 380 / 50 / 4
    # Quantization noise on the raw inner product scales with the
    # document magnitude (~2% of ||v|| at 4 bits), so tolerate that.
    for got, want, mag in zip(res.similarities, raw, POS_MAGS):
        assert got == pytest.approx(want, abs=0.03 * mag)


def test_llama_cosine_ranking_matches_simple_reference():
    pytest.importorskip("llama_index.core")
    from llama_index.core.vector_stores.simple import SimpleVectorStore

    from turbovec.llama_index import TurboQuantVectorStore

    docs, query = directed_docs(PARITY_COS, PARITY_MAGS)
    ref = SimpleVectorStore()
    ref.add(_li_nodes(docs))
    ref_ids = list(ref.query(_li_query(query, 6)).ids)

    store = TurboQuantVectorStore()
    store.add(_li_nodes(docs))
    got_ids = list(store.query(_li_query(query, 6)).ids)
    assert got_ids == ref_ids


def test_llama_mode_round_trips_through_persist(tmp_path):
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    for mode in ("cosine", "dot_product"):
        store = TurboQuantVectorStore(similarity=mode)
        store.add(_li_nodes(docs))
        before = store.query(_li_query(query, 3))
        store.persist(str(tmp_path / mode / "vector_store.json"))
        loaded = TurboQuantVectorStore.from_persist_path(
            str(tmp_path / mode / "vector_store.json")
        )
        assert loaded.similarity == mode
        after = loaded.query(_li_query(query, 3))
        assert after.ids == before.ids
        assert after.similarities == before.similarities


def test_llama_to_dict_from_dict_round_trips_similarity():
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    store = TurboQuantVectorStore(similarity="dot_product")
    config = store.to_dict()
    assert config["similarity"] == "dot_product"
    rebuilt = TurboQuantVectorStore.from_dict(config)
    assert rebuilt.similarity == "dot_product"


def test_llama_legacy_sidecar_loads_as_dot_product_with_identical_scores():
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    exp = load_expected()
    query = np.asarray(exp["query"], dtype=np.float32)
    store = TurboQuantVectorStore.from_persist_path(
        str(FIXTURES / "llama_index" / "store.json")
    )
    assert store.similarity == "dot_product"
    res = store.query(_li_query(query, 3))
    for (gid, gscore), (wid, wscore) in zip(
        zip(res.ids, res.similarities), exp["llama_index"]
    ):
        assert gid == wid
        assert gscore == pytest.approx(wscore, rel=1e-6)


def test_llama_zero_vectors_score_zero_under_cosine():
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    docs, query = directed_docs([0.5], [3.0])
    all_docs = np.vstack([docs, np.zeros((1, DIM), dtype=np.float32)])
    store = TurboQuantVectorStore()
    store.add(_li_nodes(all_docs))
    res = store.query(_li_query(query, 2))
    scores = dict(zip(res.ids, res.similarities))
    assert scores["n0"] == pytest.approx(0.5, abs=0.02)
    assert scores["n1"] == pytest.approx(0.0, abs=1e-6)


def test_llama_rejects_unknown_similarity():
    pytest.importorskip("llama_index.core")
    from turbovec.llama_index import TurboQuantVectorStore

    with pytest.raises(ValueError, match="similarity"):
        TurboQuantVectorStore(similarity="l2")


# =====================================================================
# Haystack
# =====================================================================


def _hs_docs(docs: np.ndarray):
    from haystack import Document

    return [
        Document(id=f"h{i}", content=f"c{i}", embedding=docs[i].tolist())
        for i in range(len(docs))
    ]


def test_haystack_scale_score_distinct_and_ordered_under_cosine_default():
    # Wave-8 breakage 3: with non-unit embeddings the DEFAULT cosine
    # branch of scale_score collapsed distinct raw scores to 1.0,
    # violating the "same ranking, mapped into [0, 1]" contract. Under
    # the cosine mode the scaled scores are distinct and order-preserving.
    pytest.importorskip("haystack")
    from turbovec.haystack import TurboQuantDocumentStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    store = TurboQuantDocumentStore(dim=DIM)
    store.write_documents(_hs_docs(docs))
    out = store.embedding_retrieval(
        query_embedding=query.tolist(), top_k=3, scale_score=True
    )
    assert [d.id for d in out] == ["h0", "h1", "h2"]
    scores = [d.score for d in out]
    assert scores[0] > scores[1] > scores[2]
    for got, want in zip(scores, [0.975, 0.75, 0.55]):
        assert got == pytest.approx(want, abs=0.02)


def test_haystack_dot_product_mode_keeps_sigmoid_scale_and_raw_ranking():
    pytest.importorskip("haystack")
    import math

    from turbovec.haystack import TurboQuantDocumentStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    store = TurboQuantDocumentStore(
        dim=DIM, embedding_similarity_function="dot_product"
    )
    store.write_documents(_hs_docs(docs))
    raw = [
        d.score
        for d in store.embedding_retrieval(query_embedding=query.tolist(), top_k=3)
    ]
    # Raw inner products, magnitude-aware: ~380 / 50 / 4. Quantization
    # noise scales with the document magnitude (~2% of ||v|| at 4 bits).
    for got, want, mag in zip(raw, [380.0, 50.0, 4.0], POS_MAGS):
        assert got == pytest.approx(want, abs=0.03 * mag)
    scaled = [
        d.score
        for d in store.embedding_retrieval(
            query_embedding=query.tolist(), top_k=3, scale_score=True
        )
    ]
    for got, r in zip(scaled, raw):
        assert got == pytest.approx(1.0 / (1.0 + math.exp(-r / 100.0)), abs=1e-6)


def test_haystack_cosine_ranking_matches_inmemory_reference():
    pytest.importorskip("haystack")
    from haystack.document_stores.in_memory import InMemoryDocumentStore

    from turbovec.haystack import TurboQuantDocumentStore

    docs, query = directed_docs(PARITY_COS, PARITY_MAGS)
    ref = InMemoryDocumentStore(embedding_similarity_function="cosine")
    ref.write_documents(_hs_docs(docs))
    ref_ids = [
        d.id
        for d in ref.embedding_retrieval(query_embedding=query.tolist(), top_k=6)
    ]

    store = TurboQuantDocumentStore(dim=DIM)
    store.write_documents(_hs_docs(docs))
    got_ids = [
        d.id
        for d in store.embedding_retrieval(query_embedding=query.tolist(), top_k=6)
    ]
    assert got_ids == ref_ids


def test_haystack_mode_round_trips_through_save_load(tmp_path):
    pytest.importorskip("haystack")
    from turbovec.haystack import TurboQuantDocumentStore

    docs, query = directed_docs(POS_COS, POS_MAGS)
    for mode in ("cosine", "dot_product"):
        store = TurboQuantDocumentStore(
            dim=DIM, embedding_similarity_function=mode
        )
        store.write_documents(_hs_docs(docs))
        before = [
            (d.id, d.score)
            for d in store.embedding_retrieval(query_embedding=query.tolist(), top_k=3)
        ]
        store.save_to_disk(tmp_path / mode)
        loaded = TurboQuantDocumentStore.load_from_disk(tmp_path / mode)
        assert loaded.embedding_similarity_function == mode
        assert loaded._vectors_normalized == (mode == "cosine")
        after = [
            (d.id, d.score)
            for d in loaded.embedding_retrieval(query_embedding=query.tolist(), top_k=3)
        ]
        assert after == before


def test_haystack_legacy_sidecar_loads_raw_with_identical_scores():
    # A pre-mode side-car (schema v2, embedding_similarity_function
    # recorded but vectors stored raw) must keep byte-identical behavior:
    # raw queries, raw scores, and the recorded function still selecting
    # the scale_score formula — even though that formula saturates on raw
    # inner products (the very wave-8 defect; fixing it for old stores
    # would silently change their scores, so they keep their behavior).
    pytest.importorskip("haystack")
    from turbovec.haystack import TurboQuantDocumentStore

    exp = load_expected()
    query = np.asarray(exp["query"], dtype=np.float32)
    store = TurboQuantDocumentStore.load_from_disk(FIXTURES / "haystack")
    assert store.embedding_similarity_function == "cosine"
    assert store._vectors_normalized is False
    raw = [
        (d.id, d.score)
        for d in store.embedding_retrieval(query_embedding=query.tolist(), top_k=3)
    ]
    for (gid, gscore), (wid, wscore) in zip(raw, exp["haystack"]):
        assert gid == wid
        assert gscore == pytest.approx(wscore, rel=1e-6)
    scaled = [
        (d.id, d.score)
        for d in store.embedding_retrieval(
            query_embedding=query.tolist(), top_k=3, scale_score=True
        )
    ]
    for (gid, gscore), (wid, wscore) in zip(scaled, exp["haystack_scaled"]):
        assert gid == wid
        assert gscore == pytest.approx(wscore, rel=1e-6)


def test_haystack_legacy_store_new_writes_stay_raw(tmp_path):
    # Writing into a legacy-loaded store must not normalize the new
    # vectors — mixing normalized and raw rows in one index would
    # corrupt the ranking. The whole store stays raw.
    pytest.importorskip("haystack")
    from haystack import Document

    from turbovec.haystack import TurboQuantDocumentStore

    exp = load_expected()
    store = TurboQuantDocumentStore.load_from_disk(FIXTURES / "haystack")
    docs, query = directed_docs([0.5], [8.0], dim=exp["dim"])
    store.write_documents(
        [Document(id="new", content="new", embedding=docs[0].tolist())]
    )
    out = store.embedding_retrieval(query_embedding=(2.0 * query).tolist(), top_k=4)
    scores = {d.id: d.score for d in out}
    # Raw inner product = 2 * 8 * 0.5 = 8, not the cosine 0.5 — the new
    # row went in raw and the query ran raw.
    assert scores["new"] == pytest.approx(8.0, rel=0.05)


def test_haystack_zero_vectors_score_zero_under_cosine():
    pytest.importorskip("haystack")
    from haystack import Document

    from turbovec.haystack import TurboQuantDocumentStore

    docs, query = directed_docs([0.5], [3.0])
    store = TurboQuantDocumentStore(dim=DIM)
    store.write_documents(_hs_docs(docs))
    store.write_documents(
        [Document(id="zero", content="z", embedding=[0.0] * DIM)]
    )
    out = store.embedding_retrieval(query_embedding=query.tolist(), top_k=2)
    scores = {d.id: d.score for d in out}
    assert scores["h0"] == pytest.approx(0.5, abs=0.02)
    assert scores["zero"] == pytest.approx(0.0, abs=1e-6)


def test_haystack_rejects_unknown_similarity_function():
    pytest.importorskip("haystack")
    from turbovec.haystack import TurboQuantDocumentStore

    with pytest.raises(ValueError, match="embedding_similarity_function"):
        TurboQuantDocumentStore(dim=DIM, embedding_similarity_function="l2")


# =====================================================================
# Agno
# =====================================================================


def _agno_db(docs: np.ndarray, query: np.ndarray, **kwargs):
    pytest.importorskip("agno")
    from agno.knowledge.document import Document

    from turbovec.agno import TurboQuantVectorDb

    class E:
        enable_batch = False
        dimensions = docs.shape[1]

        def get_embedding(self, text):
            if text.startswith("doc"):
                return docs[int(text[3:])].tolist()
            return query.tolist()

        def get_embedding_and_usage(self, text):
            return self.get_embedding(text), None

    db = TurboQuantVectorDb(embedder=E(), **kwargs)
    db.create()
    db.insert(
        "hash-sim", [Document(content=f"doc{i}") for i in range(len(docs))]
    )
    return db


def test_agno_similarity_threshold_meaningful_under_cosine_default():
    # Wave-8 breakage 2 (fixed side): similarity_threshold compares
    # against (raw + 1) / 2, which under the cosine default is a true
    # [0, 1] relevance. A high threshold keeps only the genuinely close
    # match instead of admitting everything.
    docs, query = directed_docs(POS_COS, POS_MAGS)
    db = _agno_db(docs, query, similarity_threshold=0.9)
    got = [d.content for d in db.search("the query", limit=3)]
    assert got == ["doc0"]  # relevances ~0.975 / 0.75 / 0.55


def test_agno_similarity_threshold_keeps_best_negatives_under_cosine():
    # All-negative cosines map to small-but-distinct relevances
    # (0.4 / 0.2 / 0.01): a small threshold keeps the two best matches
    # instead of discarding everything.
    docs, query = directed_docs(NEG_COS, NEG_MAGS)
    db = _agno_db(docs, query, similarity_threshold=0.05)
    got = [d.content for d in db.search("the query", limit=3)]
    assert got == ["doc0", "doc1"]


def test_agno_similarity_threshold_inert_under_dot_product():
    # Explicit max_inner_product opt-in pins the old raw behavior, where
    # the threshold is effectively inert on non-unit embeddings:
    # all-negative IPs discard everything at threshold 0.01, and
    # all-positive-large IPs admit everything at threshold 0.99.
    pytest.importorskip("agno")
    from agno.vectordb.distance import Distance

    docs, query = directed_docs(NEG_COS, NEG_MAGS)
    db = _agno_db(
        docs,
        query,
        distance=Distance.max_inner_product,
        similarity_threshold=0.01,
    )
    assert db.search("the query", limit=3) == []

    docs, query = directed_docs(POS_COS, POS_MAGS)
    db = _agno_db(
        docs,
        query,
        distance=Distance.max_inner_product,
        similarity_threshold=0.99,
    )
    assert len(db.search("the query", limit=3)) == 3


def test_agno_cosine_ranking_matches_cosine_order():
    # agno's in-tree LanceDb is the drop-in reference, but as of agno
    # 2.8 its wrapper never forwards the distance metric to the query
    # builder, so an un-indexed LanceDb table searches by L2 regardless
    # of distance=Distance.cosine — it cannot serve as a cosine oracle.
    # Assert against the analytic cosine ranking instead, which the
    # LangChain / Haystack / LlamaIndex references (same geometry) agree
    # with in their parity tests above.
    docs, query = directed_docs(PARITY_COS, PARITY_MAGS)
    db = _agno_db(docs, query)
    got = [d.content for d in db.search("the query", limit=6)]
    want = [f"doc{i}" for i in np.argsort(-np.asarray(PARITY_COS))[:6]]
    assert got == want


def test_agno_mode_round_trips_through_save_create(tmp_path):
    pytest.importorskip("agno")
    from agno.vectordb.distance import Distance

    from turbovec.agno import TurboQuantVectorDb

    docs, query = directed_docs(POS_COS, POS_MAGS)
    for mode in (Distance.cosine, Distance.max_inner_product):
        path = tmp_path / mode.value
        db = _agno_db(docs, query, distance=mode, path=str(path))
        before = [d.content for d in db.search("the query", limit=3)]
        db.save()

        reloaded = TurboQuantVectorDb(
            embedder=db.embedder, distance=mode, path=str(path)
        )
        reloaded.create()
        assert reloaded.distance == mode
        after = [d.content for d in reloaded.search("the query", limit=3)]
        assert after == before


def test_agno_load_rejects_conflicting_recorded_mode(tmp_path):
    pytest.importorskip("agno")
    from agno.vectordb.distance import Distance

    from turbovec.agno import TurboQuantVectorDb

    docs, query = directed_docs(POS_COS, POS_MAGS)
    db = _agno_db(
        docs, query, distance=Distance.max_inner_product, path=str(tmp_path)
    )
    db.save()

    # The construct-then-create() shape means the store already has a
    # mode when the load runs: a conflicting recorded mode is an error,
    # not a silent adoption.
    other = TurboQuantVectorDb(
        embedder=db.embedder, distance=Distance.cosine, path=str(tmp_path)
    )
    with pytest.raises(ValueError, match="distance"):
        other.create()


def test_agno_legacy_sidecar_loads_as_max_inner_product_with_identical_scores():
    pytest.importorskip("agno")
    from agno.vectordb.distance import Distance

    from turbovec.agno import TurboQuantVectorDb

    exp = load_expected()
    query = np.asarray(exp["query"], dtype=np.float32)
    docs = np.asarray(exp["doc_vectors"], dtype=np.float32)

    class E:
        enable_batch = False
        dimensions = exp["dim"]

        def get_embedding(self, text):
            if text.startswith("doc"):
                return docs[int(text[3])].tolist()
            return query.tolist()

        def get_embedding_and_usage(self, text):
            return self.get_embedding(text), None

    # Constructed with the (cosine) default, but the v1 side-car predates
    # the recorded mode and holds raw vectors: the load adopts
    # max_inner_product and scoring is unchanged from the store that
    # wrote the file.
    db = TurboQuantVectorDb(embedder=E(), path=str(FIXTURES / "agno"))
    db.create()
    assert db.distance == Distance.max_inner_product
    got = [d.content for d in db.search("query text", limit=3)]
    assert got == exp["agno"]
    q = np.ascontiguousarray(query[None, :])
    scores, handles = db._index.search(q, 3)
    for (h, s), (wh, ws) in zip(
        zip(handles[0], scores[0]), exp["agno_raw"]
    ):
        assert int(h) == wh
        assert float(s) == pytest.approx(ws, rel=1e-6)


def test_agno_zero_vectors_score_zero_under_cosine():
    pytest.importorskip("agno")
    docs, query = directed_docs([0.5], [3.0])
    all_docs = np.vstack([docs, np.zeros((1, DIM), dtype=np.float32)])
    db = _agno_db(all_docs, query)
    # No threshold: both docs come back; the zero vector ranks last with
    # scaled similarity (0 + 1) / 2 = 0.5 — i.e. raw score 0. Verify via
    # a threshold sitting between the two.
    got = [d.content for d in db.search("the query", limit=2)]
    assert got == ["doc0", "doc1"]
    db2 = _agno_db(all_docs, query, similarity_threshold=0.6)
    assert [d.content for d in db2.search("the query", limit=2)] == ["doc0"]


def test_agno_rejects_l2_distance():
    pytest.importorskip("agno")
    from agno.vectordb.distance import Distance

    from turbovec.agno import TurboQuantVectorDb

    class E:
        dimensions = DIM

        def get_embedding(self, text):
            return [0.0] * DIM

    with pytest.raises(ValueError, match="distance"):
        TurboQuantVectorDb(embedder=E(), distance=Distance.l2)
